### ISSUE TITLE
Suggestion for consolidationg code

### ISSUE THREAD

**Issue by cslotboom** [volkanozsarac/ModalAnalysis-OpenSeespy#2]
Hey, I was just playing around with this today!
Looking at your code, I had a suggestion that could be used to cut down on some of the length.
You have two blocks of code nearly identical, except for the function they are using, e.g.

```
print('\nModal Periods and Frequencies')
f.write('Modal Periods and Frequencies\n')
```

Instead we could create a function called something like printModesData(Mratios, Mfactors, ...., printFunction = print)
This function would take in the print function you want, i.e. f.write or print.

```
 if outname != None:
    with open(outname+'.csv','w', encoding='utf-32') as f:
        printModesData(arguments,  printFunction = f.write)

....

if pflag == 1:   
    printModesData(arguments, printFunction = print)
```

There might be a few complications passing f.write - the actual file might need to be passed as well..

Just a thought.

**Comment by volkanozsarac** [comment]
Thank you for the feedback @cslotboom, I see your point, I have consolidated the function. Please see the updated version, I followed a similar similar idea.

**Comment by cslotboom** [comment]
Yeah what you did makes sense! Looks great, so much shorter.

Sorry, I know it was unsolicited advice haha. These things just jump out at me.

**Comment by volkanozsarac** [comment]
No worries, it is a legit suggestion. My coding is not so amusing yet, I am still working on improvements ahaha
